FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ./*.sln ./
COPY EncounterDaily.Core/*.csproj EncounterDaily.Core/
COPY EncounterDaily.Infrastructure/*.csproj EncounterDaily.Infrastructure/
COPY EncounterDaily.Services/*.csproj EncounterDaily.Services/
COPY EncounterDaily.API/*.csproj EncounterDaily.API/
RUN dotnet restore EncounterDaily.API/EncounterDaily.API.csproj

COPY . .
RUN dotnet publish EncounterDaily.API/EncounterDaily.API.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 5000

COPY --from=build /app .
COPY seed-data ./seed-data

ENV ASPNETCORE_URLS=http://+:5000
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "EncounterDaily.API.dll"]
