import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outFile = join(__dirname, '..', 'src', 'environments', 'version.ts');

function run(cmd) {
  try {
    return execSync(cmd, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

const commitCount = run('git rev-list --count HEAD');
const shortHash  = run('git rev-parse --short HEAD');

let label = 'dev';
if (commitCount) {
  label = commitCount;
} else if (process.env.VERSION) {
  label = process.env.VERSION;
}

writeFileSync(outFile, `// Auto-generated by scripts/git-version.mjs — do not edit
export const appVersion = 'v${label}';\n`);
